notifications:
  email: false
  slack:
    rooms:
        - christopherjbischoff:pfGkxBzlRL76WzPenVJMjwzm#alerts
    on_success: change # default: always
    on_failure: always # default: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

language: generic
env:
  global:
  - access_key_id: "$AWS_ACCESS_KEY_ID"
  - secret_access_key: "$AWS_SECRET_ACCESS_KEY"

before_deploy:
 - curl -fSL "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip" -o terraform.zip
 - sudo unzip terraform.zip -d /opt/terraform
 - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
 - rm -f terraform.zip

deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    repo: cjbischoff/tf-aws-account
    branch: master
